apiVersion: v1
kind: Service
metadata:
  name: lms-api
  namespace: autolearnpro
  labels:
    app: lms-api
spec:
  selector:
    app: lms-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
