global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gpu'
    static_configs:
      - targets: ['nvidia-smi-exporter:9401']

  - job_name: 'docker'
    static_configs:
      - targets: ['prometheus:9090']
